#!/bin/bash

FILE_PO='oxyos-welcome.po'

bash --dump-po-strings ../oxyos-welcome > "$FILE_PO"

for curFile in ../lib-oxyos-welcome/*; do
    bash --dump-po-strings "$curFile" >> "$FILE_PO"
done

exit 0
